name: latex-builder
# Automatically builds LaTex curriculum and push the latest PDF back to GitHub    git rm -rf . after hey3

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    env:
      MANUSCRIPT_PATH: curriculum/cv # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex # eventually add -shell-escape if needed
      BIBTEX: bibtex

    steps: 
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra
    - name: Build paper
      run: |
        cd ${MANUSCRIPT_PATH%/*}
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        ${BIBTEX} ${MANUSCRIPT_PATH##*/}.aux
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        echo 'hey1'
        git rm -rf .github/
        echo 'hey2'
        cd ${MANUSCRIPT_PATH%/*}
        echo 'hey3'  
        echo 'hey4'
        git add -f ${MANUSCRIPT_PATH##*/}.pdf
        echo 'hey5'
        git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
