name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: curriculum/cv.tex
    - name: Check pdf file
      run: |
        file curriculum/cv.pdf | grep -q ' PDF '
    - name: Upload curriculum/cv.pdf
      run: |
        set -e
        # configure git
        git config --global user.name "Guillaume-Garrigos"
        git config --global user.email "guillaume.garrigos@lpsm.paris"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 git@github.com:Guillaume-Garrigos/website.git "$GITHUB_WORKSPACE/website"
        cp -f curriculum/cv.pdf "$GITHUB_WORKSPACE/website/file/cv.pdf"
        cd "$GITHUB_WORKSPACE/website"
        git add file/cv.pdf
        git diff --exit-code HEAD -- file/cv.pdf && exit 0
        git commit -m "[github actions] update cv"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
