# This workflow automatically compiles cv.tex in the folder curriculum/ and creates cv.pdf
# Actually also compiles a second cv_long version of the curriculum
# This Github Action is triggered by modifications to the data in the _data/ folder.
name: Latex Compiler
on:
  push:
    paths: # any modifications on those files will trigger the Action
      - '_data/diffusion.csv'
      - '_data/talks.csv'
      - '_data/teaching.csv'
      - '_data/papers.yml'
      - 'curriculum/cv.tex'
      - 'curriculum/cv_long.tex'
      - '.github/workflows/latex.trigger' # this is for debugging, sometimes I jsut wanna trigger without modifying my data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master
    - name: Compile Latex Document
      uses: Guillaume-Garrigos/latex-action@master
      with:
        root_file: |
          cv.tex
          cv_long.tex
        working_directory: curriculum
    - name: Check pdf files
      run: |
        file curriculum/cv.pdf | grep -q ' PDF '
        file curriculum/cv_long.pdf | grep -q ' PDF '
    - name: Commit files
      run: |
        git config --local user.email "guillaume.garrigos@lpsm.paris"
        git config --local user.name "Guillaume-Garrigos"
        git add curriculum/cv.pdf
        git add curriculum/cv_long.pdf
        git commit -m "[Github Action] Compile cv and create cv.pdf and cv_long.pdf" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
