name: Latex Compiler
on:
  push:
    paths:
      - 'curriculum/test.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master
    - name: Compile Latex Document
      uses: xu-cheng/latex-action@master
      with:
        root_file: test.tex
        working_directory: curriculum
    - name: Check pdf files
      run: |
        file curriculum/test.pdf | grep -q ' PDF '
    - name: Commit files
      run: |
        git config --local user.email "guillaume.garrigos@lpsm.paris"
        git config --local user.name "Guillaume-Garrigos"
        git add curriculum/test.pdf
        git commit -m "Add compiled Latex -> PDF document" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
