# This workflow automaticallty updates data when adding a new paper
# First runs a python script to compile the data and create file easy to parse by latex
# Second updates the curriculum in latex

name: Papers update
on:
  push:
    paths: # any modifications on those files will trigger the Action
      - '_data/papers.yml'
      - '.github/workflows/papers.trigger' # this is for debugging, sometimes I jsut wanna trigger without modifying my data

jobs:

  job_python:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository # needed for acessing files from the repo
      uses: actions/checkout@master
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
    - name: Execute python script # run file
      run: |
        python _data/scripts/papers.py
    - name: Commit files
      run: |
        git config --local user.email "guillaume.garrigos@lpsm.paris"
        git config --local user.name "Guillaume-Garrigos"
        git add _data/compiled/papers.csv
        git add _data/compiled/papers.yml
        git commit -m "[Github Action] Compile papers.yml in _data/compiled/" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  job_latex:
    needs: job_python # don't start latex before python is done creating the files latex needs
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master
      with:
        ref: master
    - name: Compile Latex Document
      uses: Guillaume-Garrigos/latex-action@master
      with:
        root_file: |
          cv.tex
          cv_long.tex
        working_directory: curriculum
    - name: Check pdf files
      run: |
        file curriculum/cv.pdf | grep -q ' PDF '
        file curriculum/cv_long.pdf | grep -q ' PDF '
    - name: Commit files
      run: |
        git config --local user.email "guillaume.garrigos@lpsm.paris"
        git config --local user.name "Guillaume-Garrigos"
        git add curriculum/cv.pdf
        git add curriculum/cv_long.pdf
        git commit -m "[Github Action] Compile cv and create cv.pdf and cv_long.pdf" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
