# This workflow automaticallty runs a python script
# goal is to manipulate some yaml files behind the scenes

name: Python Runner
on:
  push:
    paths: # any modifications on those files will trigger the Action
      - '_data/papers.yml'
      - '.github/workflows/python.trigger' # this is for debugging, sometimes I jsut wanna trigger without modifying my data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository # needed for acessing files from the repo
      uses: actions/checkout@master
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
    - name: Execute python script # run file
      run: |
        python _data/scripts/papers.py
    - name: Commit files
      run: |
        git config --local user.email "guillaume.garrigos@lpsm.paris"
        git config --local user.name "Guillaume-Garrigos"
        git add _data/compiled/papers.csv
        git add _data/compiled/papers.yml
        git commit -m "[Github Action] Compile papers.yml in _data/compiled/" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
